[{"name": "test.test_last_week.LastWeek.test_artist", "status": "failed", "message": "False is not true : Expected a nan on row 35 column Artist!", "passed": false, "points": ["p04-15.1"], "backtrace": ["  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 615, in run\n    testMethod()\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part04-e15_last_week/test/test_last_week.py\", line 75, in test_artist\n    self.check_column(self.df.Artist, artists, [35,38,39,40], \"Artist\")\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part04-e15_last_week/test/test_last_week.py\", line 32, in check_column\n    msg=\"Expected a nan on row %i column %s!\" % (row, column_name))\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 692, in assertTrue\n    raise self.failureException(msg)\n"]}, {"name": "test.test_last_week.LastWeek.test_base", "status": "failed", "message": "\nArrays are not equal\nIncorrect Pos column!\nx and y nan location mismatch:\n x: array([ 1.,  3.,  4.,  9.,  6.,  2.,  7., 10.,  5.,  8., 12., 16., 21.,\n       15., 11., 14., 17., 18., 19., 24., 22., 30., 13., 31., 25., 23.,\n       20., 27., 28., 38., 35., 26., 34., 33., 29., 39., nan, nan, nan,\n       nan])\n y: array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,\n       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,\n       35, 36, 37, 38, 39, 40])", "passed": false, "points": ["p04-15.1"], "backtrace": ["  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 615, in run\n    testMethod()\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part04-e15_last_week/test/test_last_week.py\", line 39, in test_base\n    np.testing.assert_array_equal(self.df.Pos, range(1,41), err_msg=\"Incorrect Pos column!\")\n", "  File \"/home/vins/anaconda3/lib/python3.7/site-packages/numpy/testing/_private/utils.py\", line 904, in assert_array_equal\n    verbose=verbose, header='Arrays are not equal')\n", "  File \"/home/vins/anaconda3/lib/python3.7/site-packages/numpy/testing/_private/utils.py\", line 757, in assert_array_compare\n    flagged = func_assert_same_pos(x, y, func=isnan, hasval='nan')\n", "  File \"/home/vins/anaconda3/lib/python3.7/site-packages/numpy/testing/_private/utils.py\", line 733, in func_assert_same_pos\n    raise AssertionError(msg)\n"]}, {"name": "test.test_last_week.LastWeek.test_lw", "status": "failed", "message": "False is not true : Expected a nan on row 1 column LW!", "passed": false, "points": ["p04-15.2"], "backtrace": ["  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 615, in run\n    testMethod()\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part04-e15_last_week/test/test_last_week.py\", line 105, in test_lw\n    self.check_column(self.df.LW, [], range(1,41), \"LW\")\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part04-e15_last_week/test/test_last_week.py\", line 32, in check_column\n    msg=\"Expected a nan on row %i column %s!\" % (row, column_name))\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 692, in assertTrue\n    raise self.failureException(msg)\n"]}, {"name": "test.test_last_week.LastWeek.test_peak_pos", "status": "failed", "message": "False is not true : Expected a nan on row 6 column Peak Pos!", "passed": false, "points": ["p04-15.2"], "backtrace": ["  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 615, in run\n    testMethod()\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part04-e15_last_week/test/test_last_week.py\", line 94, in test_peak_pos\n    [6,9,15,16,23,27,29,32, 35, 38,39,40], \"Peak Pos\")\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part04-e15_last_week/test/test_last_week.py\", line 32, in check_column\n    msg=\"Expected a nan on row %i column %s!\" % (row, column_name))\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 692, in assertTrue\n    raise self.failureException(msg)\n"]}, {"name": "test.test_last_week.LastWeek.test_publisher", "status": "failed", "message": "False is not true : Expected a nan on row 35 column Publisher!", "passed": false, "points": ["p04-15.1"], "backtrace": ["  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 615, in run\n    testMethod()\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part04-e15_last_week/test/test_last_week.py\", line 86, in test_publisher\n    self.check_column(self.df.Publisher, publishers, [35,38,39,40], \"Publisher\")\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part04-e15_last_week/test/test_last_week.py\", line 32, in check_column\n    msg=\"Expected a nan on row %i column %s!\" % (row, column_name))\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 692, in assertTrue\n    raise self.failureException(msg)\n"]}, {"name": "test.test_last_week.LastWeek.test_title", "status": "failed", "message": "False is not true : Expected a nan on row 35 column Title!", "passed": false, "points": ["p04-15.1"], "backtrace": ["  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 615, in run\n    testMethod()\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part04-e15_last_week/test/test_last_week.py\", line 58, in test_title\n    self.check_column(self.df.Title, titles, [35,38,39,40], \"Title\")\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part04-e15_last_week/test/test_last_week.py\", line 32, in check_column\n    msg=\"Expected a nan on row %i column %s!\" % (row, column_name))\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 692, in assertTrue\n    raise self.failureException(msg)\n"]}, {"name": "test.test_last_week.LastWeek.test_woc", "status": "failed", "message": "False is not true : Expected a nan on row 35 column WoC!", "passed": false, "points": ["p04-15.1"], "backtrace": ["  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 615, in run\n    testMethod()\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part04-e15_last_week/test/test_last_week.py\", line 101, in test_woc\n    self.check_column(self.df.WoC, wocs, [35,38,39,40], \"WoC\")\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part04-e15_last_week/test/test_last_week.py\", line 32, in check_column\n    msg=\"Expected a nan on row %i column %s!\" % (row, column_name))\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 692, in assertTrue\n    raise self.failureException(msg)\n"]}]